FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package.json
RUN npm install

FROM deps AS build
WORKDIR /app
COPY tsconfig.json .eslintrc.cjs ./
COPY src ./src
COPY test ./test
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package.json
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 4000
CMD ["node", "dist/index.js"]
